apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- tstream_backendapi.yaml
- tstream_ingress.yaml
images:
- name: harbor.ww.home/dojo/news-streams
  newName: harbor.ww.home/dojo/news-streams
