apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: news-stream
  name: tstream-backendapi
  labels:
    app: news-stream
    component: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-stream
      component: backend-api
  template:
    metadata:
      labels:
        app: news-stream
        component: backend-api
    spec:
      containers:
        - name: tstream-backendapi
          image: harbor.ww.home/dojo/news-streams:python-49
          ports:
            - name: readiness-port
              containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: readiness-port
            failureThreshold: 2
            periodSeconds: 30

          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI
            - name: PYTHONPATH
              value: "."
          command:
            - python3
          args:
            - /src/manage.py
            - runserver